//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadDBConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.ClassInfo = new HashSet<ClassInfo>();
        }
    
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserPsw { get; set; }
        public string Describe { get; set; }
        public string Phone { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<ClassInfo> ClassInfo { get; set; }
        public virtual UserInfo UserInfo1 { get; set; }
        public virtual UserInfo UserInfo2 { get; set; }
    }
}
